### ISSUE TITLE
yii2-swagger-ui need help

### ISSUE THREAD

**Issue by sergey-kukosh** [machour/yii2-swagger-ui#1]
Hi. There is a need to use a swagger in my project. But I do not understand how to use your library. Can you explain more about how to use your library in the project? Thank you.

**Comment by machour** [comment]
Hi,

This is the User Interface (html/js) for Swagger. Simply follow the instructions found in the README file : https://github.com/machour/yii2-swagger-ui/blob/master/README.md

Install it, copy the files from 'views' into your own view directory, configure the URL (in the view) from where the swagger interface will read its information (the swagger json file) and then make an action that will display the view. That should be it.

Also check https://github.com/machour/yii2-swagger-api which allow you to automatically generate your swagger json file by parsing your API controller.
